In [1]:
import numpy as np
import pandas as pd

In [2]:
import numpy as np

y = np.array([2, 3, 4]).reshape(1, 3, 1, 1)
x = np.ones(shape, dtype=np.uint8)
shape = (1000, 3, 32, 32)
out = np.empty(shape, dtype=np.uint8)
N, C, W, H = shape
for n in range(N):
    for channel in range(C):
        for w in range(W):
            for h in range(H):
                out[n, channel, w, h] = x[n, channel, w, h] * y[0, channel, 0, 0]

NameError: name 'shape' is not defined

In [3]:
rng = np.random.default_rng(seed=1)
print(rng.integers(low=1, high=101, size=(3, 2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [4]:
np.random.seed(seed=1)

print(np.random.uniform(low=-1, high=1, size=(3, 2)))

[[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]


In [5]:
rng = np.random.default_rng() 
array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print(array)

[2 5 4 3 1]


In [6]:
rng = np.random.default_rng()
fruits = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])
rng.shuffle(fruits)
fruit = rng.choice(fruits, size=(3, 2))
print(fruits)
print(fruit)

['cherry' 'banana' 'elderberry' 'date' 'apple']
[['apple' 'cherry']
 ['cherry' 'date']
 ['apple' 'date']]


In [7]:
rng = np.random.default_rng()
emojis = np.array(['😀', '😂', '😎', '😍', '🤔'])
emoji = rng.choice(emojis, size=(3, 3))
print(emoji)

[['😀' '😍' '😍']
 ['😍' '🤔' '😍']
 ['😍' '😂' '😍']]


In [8]:
df = pd.DataFrame({
    "Name": [
        "Braund, Mr. Owen Harris",
        "Allen Mr. William Henry",
        "Bonnell, Miss. Elizabeth",
    ],
    "Age": [22, 35, 58],
    "Sex": ["male", "male", "female"],
}
                  )
print(df)

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1   Allen Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female


In [11]:
print(df["Age"])
print(df["Name"])
print(df["Sex"])

0    22
1    35
2    58
Name: Age, dtype: int64
0     Braund, Mr. Owen Harris
1     Allen Mr. William Henry
2    Bonnell, Miss. Elizabeth
Name: Name, dtype: object
0      male
1      male
2    female
Name: Sex, dtype: object


In [12]:
ages = pd.Series([22, 35, 58], name="Age")
print(ages)

0    22
1    35
2    58
Name: Age, dtype: int64


In [15]:
print(df["Age"].max())
print(ages.max())

58
58


In [23]:
print(df["Age"].describe())
print(df["Name"].describe())
print(df["Sex"].describe()) 

count     3.000000
mean     38.333333
std      18.230012
min      22.000000
25%      28.500000
50%      35.000000
75%      46.500000
max      58.000000
Name: Age, dtype: float64
count                           3
unique                          3
top       Braund, Mr. Owen Harris
freq                            1
Name: Name, dtype: object
count        3
unique       2
top       male
freq         2
Name: Sex, dtype: object


In [25]:
df2 = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "city": ["Warsaw", "Dallas", "London"]
})
print(df2)
print(df2["name"])
print(type(df2["name"]))

      name  age    city
0    Alice   25  Warsaw
1      Bob   30  Dallas
2  Charlie   35  London
0      Alice
1        Bob
2    Charlie
Name: name, dtype: object
<class 'pandas.core.series.Series'>
